version: '2'

services:
  # The Application
  testphpapp:
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - "DB_PORT=3307"
      - "DB_HOST=testphpdb"
    networks:
      - testphpnetwork
    restart: on-failure

  # The Web Server
  testphpweb:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes_from:
      - testphpapp
    ports:
      - "8080:80"
    networks:
      - testphpnetwork
    restart: on-failure

  # The Database
  testphpdb:
    image: mysql:8.1
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=testphpdb"
      - "MYSQL_USER=testphpuser"
      - "MYSQL_PASSWORD=testphpsecret"
      - "MYSQL_ROOT_PASSWORD=testphpsecret"
    ports:
      - "3308:3308"  # Cambiar ambos puertos a 3307
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--port=3308']  # Puerto interno configurado en 3307
    networks:
      - testphpnetwork
    restart: on-failure

networks:
  testphpnetwork:
    driver: bridge

