services:
  # The Application
  testinertiaapp:  # Nombre corregido
    build:
      context: ./
      dockerfile: ./docker/app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - "DB_PORT=3308"
      - "DB_HOST=testinertiadb"
    networks:
      - testinertianetwork
    restart: on-failure

  # The Web Server
  testinertiaweb:
    build:
      context: ./
      dockerfile: ./docker/web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    networks:
      - testinertianetwork
    restart: on-failure

  # The Database
  testinertiadb:
    image: mysql:8.1
    volumes:
      - ./dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=testinertiadb"
      - "MYSQL_USER=testinertiauser"
      - "MYSQL_PASSWORD=testinertiasecret"
      - "MYSQL_ROOT_PASSWORD=testinertiasecret"
    ports:
      - "3308:3308"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--port=3308']
    networks:
      - testinertianetwork
    restart: on-failure

networks:
  testinertianetwork:
    driver: bridge
